# Site settings
title: Anechoics
email: contact@anechoics.uk
description: Anechoics are a Bristol based improvised synthesizer band who create spacious and evolving live electronic music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anechoics.uk"
github_username:  anechoics
ilp: "$ilp.uphold.com/xZEy2Dg9nBMk"
# Build settings
markdown: kramdown
