# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anechoics 
email: contact@anechoics.uk
description: Anechoics are a Bristol based improvised synthesizer band who create spacious and evolving live electronic music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anechoics.uk" 
github_username:  anechoics
ilp: "$ilp.uphold.com/xZEy2Dg9nBMk"
# Build settings
markdown: kramdown
